config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('music/', include('music.urls')),
    path('sports/', include('sports.urls')),
    path('travel/', include('travel.urls')),
    path('', home, name='home'),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('list/', views.movie_list, name='list'),
    path('create/', views.create_movie, name='create'),
    path('detail/<int:movie_id>', views.movie_detail, name='detail'),
    path('delete/<int:movie_id>', views.movie_delete, name='delete'),
    path('update/<int:movie_id>', views.movie_update, name='update'),
]

music/urls.py
from django.urls import path
from . import views


app_name = 'music'

urlpatterns = [
    path('list/', views.music_list, name='list'),
    path('create/', views.create_album, name='create'),
    path('detail/<int:music_id>', views.album_detail, name='detail'),
    path('delete/<int:music_id>', views.album_delete, name='delete'),
    path('update/<int:music_id>', views.album_update, name='update'),
]

movies/models.py
from django.db import models
from django.shortcuts import reverse


class Movie(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    year = models.PositiveIntegerField()
    genre = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('movies:detail', args=[self.pk])

    def get_delete_url(self):
        return reverse('movies:delete', args=[self.pk])

    def get_update_url(self):
        return reverse('movies:update', args=[self.pk])

movies/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Movie


def home(request):
    return render(request,'index.html')

def movie_list(request):
    movies = Movie.objects.all()
    ctx = {'movies':movies}
    return render(request, 'movies/movie-list.html', ctx)

def create_movie(request):
    if request.method == 'POST':
        title=request.POST.get('title')
        director=request.POST.get('director')
        year=request.POST.get('year')
        genre=request.POST.get('genre')
        if title and director and year and genre:
            Movie.objects.create(
                title = title,
                director = director,
                year = year,
                genre = genre
            )
            return redirect('movies:list')
    return render(request, 'movies/movie-create.html')


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    ctx = {'movie':movie}
    return render(request, 'movies/movie-detail.html', ctx)

def movie_update(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == 'POST':
        title=request.POST.get('title')
        director=request.POST.get('director')
        year=request.POST.get('year')
        genre=request.POST.get('genre')
        if title and director and year and genre:
            movie.title = title
            movie.director = director
            movie.year = year
            movie.genre = genre
            movie.save()
            return redirect(movie.get_detail_url())
    ctx = {'movie':movie}
    return render(request, 'movies/movie-create.html', ctx)

def movie_delete(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    movie.delete()
    return redirect('movies:list')

templates/movies/movie-create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% if movie %}Update Movie {% else %}Create Movie{% endif %}</title>
</head>
<body>
  <h1>{% if movie %}Update Movie {% else %}Create Movie{% endif %}</h1>
  <form method="post">
    {% csrf_token %}
    <label for="title">Title:</label><br>
    <input id="title" type="text" name="title" value="{{ movie.title }}"><br><br>
    <label for="director">Director:</label><br>
    <input id="director" type="text" name="director" value="{{ movie.director }}"><br><br>
    <label for="year">Release Year:</label><br>
    <input id="year" type="number" name="year" value="{{ movie.year }}"><br><br>
    <label for="genre">Genre:</label><br>
    <input id="genre" type="text" name="genre" value="{{ movie.genre }}"><br><br>
    <button type="submit">{% if movie %}Update{% else %}Create{% endif %}</button>
  </form>
  <br>
  {% if movie %}
    <button><a href="{{ movie.get_detail_url }}">Back to Detail</a></button>
  {% else %}
    <button><a href="{% url 'movies:list' %}">Back to List</a></button>
  {% endif %}
</body>
</html>

templates/movies/movie-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ movie.title }}</title>
</head>
<body>
    <button><a href="{% url 'movies:list' %}">Back to List</a></button>
    <button><a href="{{ movie.get_update_url }}">Update</a></button>
    <h1>{{ movie.title }}</h1>
    <h3>Director: {{ movie.director }}</h3>
    <h3>Release Year: {{ movie.year }}</h3>
    <h3>Genre: {{ movie.genre }}</h3>
    <button><a href="{{ movie.get_delete_url }}">Delete</a></button>
</body>
</html>

templates/movies/movie-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie List</title>
</head>
<body>
    <h1>Movie List</h1>
    <button><a href="{% url 'movies:create' %}">Create Movie</a></button>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for movie in movies %}
        <a href="{{ movie.get_detail_url }}"><h3>{{ movie.title }}</h3></a>
    {% empty %}
        <h3>No Movies</h3>
    {% endfor %}
</body>
</html>