config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('music/', include('music.urls')),
    path('sports/', include('sports.urls')),
    path('travel/', include('travel.urls')),
    path('', home, name='home'),
]

music/urls.py
from django.urls import path
from . import views


app_name = 'music'

urlpatterns = [
    path('list/', views.music_list, name='list'),
    path('create/', views.create_album, name='create'),
    path('detail/<int:music_id>', views.album_detail, name='detail'),
    path('delete/<int:music_id>', views.album_delete, name='delete'),
    path('update/<int:music_id>', views.album_update, name='update'),
]

music/models.py
from django.db import models
from django.shortcuts import reverse


class Music(models.Model):
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    date = models.DateField()
    genre = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('music:detail', args=[self.pk])

    def get_delete_url(self):
        return reverse('music:delete', args=[self.pk])

    def get_update_url(self):
        return reverse('music:update', args=[self.pk])

music/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Music


def home(request):
    return render(request,'index.html')

def music_list(request):
    music = Music.objects.all()
    ctx = {'music':music}
    return render(request, 'music/music-list.html', ctx)

def create_album(request):
    if request.method == 'POST':
        title=request.POST.get('title')
        artist=request.POST.get('artist')
        date=request.POST.get('date')
        genre=request.POST.get('genre')
        if title and artist and date and genre:
            Music.objects.create(
                title = title,
                artist = artist,
                date = date,
                genre = genre
            )
            return redirect('music:list')
    return render(request, 'music/album-create.html')

def album_detail(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    ctx = {'music':music}
    return render(request, 'music/album-detail.html', ctx)

def album_update(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    if request.method == 'POST':
        title=request.POST.get('title')
        artist=request.POST.get('artist')
        date=request.POST.get('date')
        genre=request.POST.get('genre')
        if title and artist and date and genre:
            music.title = title
            music.artist = artist
            music.date = date
            music.genre = genre
            music.save()
            return redirect(music.get_detail_url())
    ctx = {'music':music}
    return render(request, 'music/album-create.html', ctx)

def album_delete(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    music.delete()
    return redirect('music:list')

templates/music/album-create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% if music %}Update Album {% else %}Create Album{% endif %}</title>
</head>
<body>
  <h1>{% if music %}Update Album {% else %}Create Album{% endif %}</h1>
  <form method="post">
    {% csrf_token %}
    <label for="title">Title:</label><br>
    <input id="title" type="text" name="title" value="{{ music.title }}"><br><br>
    <label for="artist">Artist:</label><br>
    <input id="artist" type="text" name="artist" value="{{ music.artist }}"><br><br>
    <label for="date">Release Date:</label><br>
    <input id="date" type="date" name="date" value="{{ music.date }}"><br><br>
    <label for="genre">Genre:</label><br>
    <input id="genre" type="text" name="genre" value="{{ music.genre }}"><br><br>
    <button type="submit">{% if music %}Update{% else %}Create{% endif %}</button>
  </form>
  <br>
  {% if music %}
    <button><a href="{{ music.get_detail_url }}">Back to Detail</a></button>
  {% else %}
    <button><a href="{% url 'music:list' %}">Back to List</a></button>
  {% endif %}
</body>
</html>

templates/music/album-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ music.title }}</title>
</head>
<body>
    <button><a href="{% url 'music:list' %}">Back to List</a></button>
    <button><a href="{{ music.get_update_url }}">Update</a></button>
    <h1>{{ music.title }}</h1>
    <h3>Artist: {{ music.artist }}</h3>
    <h3>Release Date: {{ music.date }}</h3>
    <h3>Genre: {{ music.genre }}</h3>
    <button><a href="{{ music.get_delete_url }}">Delete</a></button>
</body>
</html>

templates/music/music-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music Albums</title>
</head>
<body>
    <h1>Music Albums</h1>
    <button><a href="{% url 'music:create' %}">Create Album</a></button>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for album in music %}
        <a href="{{ album.get_detail_url }}"><h3>{{ album.title }}</h3></a>
    {% empty %}
        <h3>No Albums</h3>
    {% endfor %}
</body>
</html>