config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('music/', include('music.urls')),
    path('sports/', include('sports.urls')),
    path('travel/', include('travel.urls')),
    path('', home, name='home'),
]

music/urls.py
from django.urls import path
from . import views


app_name = 'music'

urlpatterns = [
    path('list/', views.music_list, name='list'),
    path('create/', views.create_album, name='create'),
    path('detail/<int:music_id>', views.album_detail, name='detail'),
    path('delete/<int:music_id>', views.album_delete, name='delete'),
    path('update/<int:music_id>', views.album_update, name='update'),
]

sports/urls.py
from django.urls import path
from . import views


app_name = 'sports'

urlpatterns = [
    path('list/', views.event_list, name='list'),
    path('create/', views.create_event, name='create'),
    path('detail/<int:event_id>', views.event_detail, name='detail'),
    path('delete/<int:event_id>', views.event_delete, name='delete'),
    path('update/<int:event_id>', views.event_update, name='update'),
]

sports/models.py
from django.db import models
from django.shortcuts import reverse


class Sport(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    date = models.DateField()
    sport_type = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('sports:detail', args=[self.pk])

    def get_delete_url(self):
        return reverse('sports:delete', args=[self.pk])

    def get_update_url(self):
        return reverse('sports:update', args=[self.pk])

sports/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Sport


def home(request):
    return render(request,'index.html')

def event_list(request):
    sports = Sport.objects.all()
    ctx = {'sports':sports}
    return render(request, 'sports/event-list.html', ctx)

def create_event(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        location=request.POST.get('location')
        date=request.POST.get('date')
        sport_type=request.POST.get('sport_type')
        if name and location and date and sport_type:
            Sport.objects.create(
                name = name,
                location = location,
                date = date,
                sport_type = sport_type
            )
            return redirect('sports:list')
    return render(request, 'sports/event-create.html')

def event_detail(request, event_id):
    sport = get_object_or_404(Sport, pk=event_id)
    ctx = {'sport':sport}
    return render(request, 'sports/event-detail.html', ctx)

def event_update(request, event_id):
    event = get_object_or_404(Sport, pk=event_id)
    if request.method == 'POST':
        name=request.POST.get('name')
        location=request.POST.get('location')
        date=request.POST.get('date')
        sport_type=request.POST.get('sport_type')
        if name and location and date and sport_type:
            event.name = name
            event.location = location
            event.date = date
            event.sport_type = sport_type
            event.save()
            return redirect(event.get_detail_url())
    ctx = {'event':event}
    return render(request, 'sports/event-create.html', ctx)

def event_delete(request, event_id):
    event = get_object_or_404(Sport, pk=event_id)
    event.delete()
    return redirect('sports:list')

templates/sports/event-create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% if event %}Update Event {% else %}Create Event{% endif %}</title>
</head>
<body>
  <h1>{% if event %}Update Event {% else %}Create Event{% endif %}</h1>
  <form method="post">
    {% csrf_token %}
    <label for="name">Event Name:</label><br>
    <input id="name" type="text" name="name" value="{{ event.name }}"><br><br>
    <label for="location">Location:</label><br>
    <input id="location" type="text" name="location" value="{{ event.location }}"><br><br>
    <label for="date">Date:</label><br>
    <input id="date" type="date" name="date" value="{{ event.date }}"><br><br>
    <label for="sport_type">Sport Type:</label><br>
    <input id="sport_type" type="text" name="sport_type" value="{{ event.sport_type }}"><br><br>
    <button type="submit">{% if event %}Update{% else %}Create{% endif %}</button>
  </form>
  <br>
  {% if event %}
    <button><a href="{{ event.get_detail_url }}">Back to Detail</a></button>
  {% else %}
    <button><a href="{% url 'sports:list' %}">Back to List</a></button>
  {% endif %}
</body>
</html>

templates/sports/event-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ sport.title }}</title>
</head>
<body>
    <button><a href="{% url 'sports:list' %}">Back to List</a></button>
    <button><a href="{{ sport.get_update_url }}">Update</a></button>
    <h1>{{ sport.name }}</h1>
    <h3>Location: {{ sport.location }}</h3>
    <h3>Date: {{ sport.date }}</h3>
    <h3>Sport Type: {{ sport.sport_type }}</h3>
    <button><a href="{{ sport.get_delete_url }}">Delete</a></button>
</body>
</html>

templates/sports/event-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sport Events</title>
</head>
<body>
    <h1>Sport Events</h1>
    <button><a href="{% url 'sports:create' %}">Create Event</a></button>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for event in sports %}
        <a href="{{ event.get_detail_url }}"><h3>{{ event.name }}</h3></a>
    {% empty %}
        <h3>No Events</h3>
    {% endfor %}
</body>
</html>