config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('music/', include('music.urls')),
    path('sports/', include('sports.urls')),
    path('travel/', include('travel.urls')),
    path('', home, name='home'),
]

music/urls.py
from django.urls import path
from . import views


app_name = 'music'

urlpatterns = [
    path('list/', views.music_list, name='list'),
    path('create/', views.create_album, name='create'),
    path('detail/<int:music_id>', views.album_detail, name='detail'),
    path('delete/<int:music_id>', views.album_delete, name='delete'),
    path('update/<int:music_id>', views.album_update, name='update'),
]

travel/urls.py
from django.urls import path
from . import views


app_name = 'travel'

urlpatterns = [
    path('list/', views.travel_list, name='list'),
    path('create/', views.create_destination, name='create'),
    path('detail/<int:travel_id>', views.travel_detail, name='detail'),
    path('delete/<int:travel_id>', views.travel_delete, name='delete'),
    path('update/<int:travel_id>', views.travel_update, name='update'),
]

travel/models.py
from django.db import models
from django.shortcuts import reverse


class Destination(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    description = models.TextField()
    popular_season = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('travel:detail', args=[self.pk])

    def get_delete_url(self):
        return reverse('travel:delete', args=[self.pk])

    def get_update_url(self):
        return reverse('travel:update', args=[self.pk])

travel/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Destination


def home(request):
    return render(request,'index.html')

def travel_list(request):
    travel = Destination.objects.all()
    ctx = {'travel':travel}
    return render(request, 'travel/travel-list.html', ctx)

def create_destination(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        country=request.POST.get('country')
        description=request.POST.get('description')
        popular_season=request.POST.get('popular_season')
        if name and country and description and popular_season:
            Destination.objects.create(
                name = name,
                country = country,
                description = description,
                popular_season = popular_season
            )
            return redirect('travel:list')
    return render(request, 'travel/travel-form.html')

def travel_detail(request, travel_id):
    travel = get_object_or_404(Destination, pk=travel_id)
    ctx = {'travel':travel}
    return render(request, 'travel/travel-detail.html', ctx)

def travel_update(request, travel_id):
    travel = get_object_or_404(Destination, pk=travel_id)
    if request.method == 'POST':
        name=request.POST.get('name')
        country=request.POST.get('country')
        description=request.POST.get('description')
        popular_season=request.POST.get('popular_season')
        if name and country and description and popular_season:
            travel.name = name
            travel.country = country
            travel.description = description
            travel.popular_season = popular_season
            travel.save()
            return redirect(travel.get_detail_url())
    ctx = {'travel':travel}
    return render(request, 'travel/travel-form.html', ctx)

def travel_delete(request, travel_id):
    travel = get_object_or_404(Destination, pk=travel_id)
    travel.delete()
    return redirect('travel:list')

templates/travel/travel-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ travel.name }}</title>
</head>
<body>
    <button><a href="{% url 'travel:list' %}">Back to List</a></button>
    <button><a href="{{ travel.get_update_url }}">Update</a></button>
    <h1>{{ travel.name }}</h1>
    <h3>Country: {{ travel.country }}</h3>
    <h3>Description: {{ travel.description }}</h3>
    <h3>Popular Season: {{ travel.popular_season }}</h3>
    <button><a href="{{ travel.get_delete_url }}">Delete</a></button>
</body>
</html>

templates/travel/travel-form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% if travel %}Update Travel Destination {% else %}Create Travel Destination{% endif %}</title>
</head>
<body>
  <h1>{% if travel %}Update Travel Destination {% else %}Create Travel Destination{% endif %}</h1>
  <form method="post">
    {% csrf_token %}
    <label for="name">Destination Name:</label><br>
    <input id="name" type="text" name="name" value="{{ travel.name }}"><br><br>
    <label for="country">Country:</label><br>
    <input id="country" type="text" name="country" value="{{ travel.country }}"><br><br>
    <label for="description">Description:</label><br>
    <textarea id="description" name="description"></textarea><br><br>
    <label for="popular_season">Popular Season:</label><br>
    <input id="popular_season" type="text" name="popular_season" value="{{ travel.popular_season }}"><br><br>
    <button type="submit">{% if travel %}Update{% else %}Create{% endif %}</button>
  </form>
  <br>
  {% if travel %}
    <button><a href="{{ travel.get_detail_url }}">Back to Detail</a></button>
  {% else %}
    <button><a href="{% url 'travel:list' %}">Back to List</a></button>
  {% endif %}
</body>
</html>

templates/travel/travel-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Travel Destinations</title>
</head>
<body>
    <h1>Travel Destinations</h1>
    <button><a href="{% url 'travel:create' %}">Create Destination</a></button>
    <button><a href="{% url 'home' %}">Back to home</a></button>
    {% for destination in travel %}
        <a href="{{ destination.get_detail_url }}"><h3>{{ destination.name }}</h3></a>
    {% empty %}
        <h3>No Destinations</h3>
    {% endfor %}
</body>
</html>